# Foreword {.unnumbered}

I've always felt that something was wrong with the current approaches
to geospatial data science in other programming languages. I remember
sitting in
[Stanford's Green library](https://en.wikipedia.org/wiki/Cecil_H._Green_Library) after a short
introductory course on GIS with R, and wondering why I had to be so
"computer sciency":

- What on Earth is a "LineString"? Isn't a "Line" a geometric object with infinite lenght?
- Why do I need to learn this low-level distinction between "raster" and "vector" data?

Something was off for sure, but it took me years after my PhD to envision
a more general approach to geospatial data science through the consistent
development of the
[GeoStats.jl](https://github.com/JuliaEarth/GeoStats.jl) framework.

I have to say, it is not easy to swim against the wave when most people
are still surfing ~20-year-old standards like the
[simple features](https://www.iso.org/standard/40114.html).
One thing I learned over the years is that geoscience is **not** simple,
is **not** 2D, and should **not** be developed **for** software engineers.

In that sense, I am one of the few rebels out there (hope you will join
us!) that devotes energy and time to educate geoscientists about this new
way of working with geospatial data. There is a long journey until the
technology reaches its full potential, but we are getting there!

We hope that the book will enlighten your understanding of some of these
issues and that you can benefit from all the **open source** software
we built over the years.